name: Just Testing

on:
  push:
    paths: ["home-manager/**", ".github/workflows/just.yml"]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix_typer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: home-manager
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          fetch-depth: 0

      - uses: extractions/setup-just@v3
        run: just

      - name: Commit changes
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(home-manager): test just run [skip ci]"
          file_pattern: home-manager/**
